### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by v0idxyz**
added eventlistener for the enter key on login form

### CODE REVIEW

**Comment by Dyplay** [comment]
> added eventlistener for the enter key on login form

Why? This woudnt make sense since this website is just made in html css and js?

**Comment by v0idxyz** [comment]
makes sense cause no one moves the mouse to log in on an actual windows login

**Comment by Dyplay** [comment]
> makes sense cause no one moves the mouse to log in on an actual windows login

Well you got a point

**Review by Dyplay — APPROVED** [review]
Alright

**Pull request merged**
